### ISSUE TITLE
Config setters should accept a config object

### ISSUE THREAD

**Issue by vitosamson** [lightswitch05/foscam-client#2]
I just accidentally overwrote my motion detection config because I only passed one arg to `.setMotionDetectConfig()`. Accepting an object would allow the user to get the config from the getter, update a specific config item, then pass that object back to the setter.

**Comment by lightswitch05** [comment]
Yes, I would like to do this with all the getters and setters, but I haven't had time to yet. Pull requests welcome

**Comment by vitosamson** [comment]
I can start taking a crack at this. How do you feel about splitting up `foscam.js` into multiple files, organized similarly to the API PDF (AV functions, user account, PTZ control, etc)?

**Comment by lightswitch05** [comment]
That is fine with me, just try to jsdoc everything. Long-term I would like to have a gulp-based build process with mocha tests that mock the actual calls. I've used this yeoman generator for other projects https://github.com/yeoman/generator-node

**Comment by lightswitch05** [comment]
Closed by #3
