### ISSUE TITLE
Android SDK

### ISSUE THREAD

**Issue by amouly** [lightswitch05/foscam-client#7]
Do you know if there is any updated SDK for Android? I've found the ZIP file hosted in this repository, but the source code it's pretty buggy and crashes every time.

Thanks for sharing this, amazing work.

**Comment by lightswitch05** [comment]
The files hosted in this repo was the newest versions that Foscam released publicly. They don't publicly release code or API documentation anymore. If you search around on their forum you'll find forms to fill out to request access to their newer versions

**Comment by lightswitch05** [comment]
Check this thread out, sorry I can't be more help:http://foscam.us/forum/new-sdk-cgi-application-t13426.html

**Comment by amouly** [comment]
Yeah, I've seen that information, and already contacted the Foscam team, but they asks a lot of questions and personal data. I just want to make my own software, don't know why is so difficult to access this information. Again, thank you for your support.
